### ISSUE TITLE
parser-util does not detect possible git+file flakerefs

### ISSUE THREAD

**Issue by ysndr** [flox/runix#43]
**Describe the bug:**

When parsing raw paths as flakerefs using the new parser-util based flakeref parser paths are always parsed as `path:` urls even if they are part of a git repository.
The old parser (in line with most nix commands) parses such paths to `git+file:`.
The benefit of `git+file:` urls is that the path can be lazily loaded into the store.
`git+file:` references also ensure that only tracked files are added meaning large `target` folders do not add up within the nix store.

**Steps to reproduce:**
1. `git clone github.com/flox/flox`
2. `flox build .#flox-bash`

Result: 

```
...
Copying <cwd>...
...
```

Expected: 

No copy

**Possible solutions***

```diff
-                  : nix::parseFlakeRef( arg, nix::absPath( "." ), true, false );
+                  : nix::parseFlakeRef( arg, nix::absPath( "." ), false, true );
```

in 

https://github.com/flox/parser-util/blob/main/main.cc#L105

or using `installable_flake_ref()` in

https://github.com/flox/runix/blob/main/crates/runix/src/flake_ref/mod.rs#L221-L222

**Comment by alex-ameen** [comment]
Did y'all try using the installable URI parser ( which handles "project context" )?

The names `resolveAndParseURI` vs. `parseURIWithFragmentAndExtendedOutputSpec` aren't exactly descriptive in that sense; but the change described in the issue here would sacrifice our ability to parse URIs without fetching and reading the filesystem to ensure that there is a valid `flake.nix` file in the source tree.

I'd be happy to add a CLI flag or something though to make this a toggle if you prefer `-r` over `-i` ( although I encourage that you compare the output of `-i` and `-l` to see if those cover your usage ). I'd want to make it a toggle so that the test suite can continue to behave as it does without needing to create real filesystem paths and phony flakes when parsing.

If I had some more context on the usage in `flox` I'd be more able to tailor the executable to those needs. For example "we need to take a `git` URI and convert `ref` into `rev`", or "we need to explode a CLI argument so that it can be written to a lock/evaluated by `nix` expressions".

**Comment by zmitchell** [comment]
I would also love to see a strict set of requirements for how and when we parse URIs in various ways, I'm kind of confused myself as to when we want to do which resolution.

I'm working on just using `-i` right now.

**Comment by zmitchell** [comment]
So I have it detecting `git+file` references, but I'm not sure how to check that it's not copying the entire directory tree during the build.

**Comment by ysndr** [comment]
Using the `-i` call works out as expected, thanks.
To resolve indirects (`flake:xyz`) we can still use the `-r` flag, or `flake metadata` in a separate call when needed.

**Comment by ysndr** [comment]
> but I'm not sure how to check that it's not copying the entire directory tree during the build.

That is an implication of `path:` references
If paths are resolved to `git+file:` as possible, nix will use the more efficient git based ingest instead.
