### ISSUE TITLE
Relicensing under a non-GPL license?

### ISSUE THREAD

**Issue by matthiasbeyer** [flox/runix#55]
Hey!

I found your project and I really like it. Would you consider relicensing it under a non-GPL license? Because of static linking, this is essentially a GPL project, which makes it impossible to use in non-GPL projects.

For example, you could use MPL to get the same effect as (L)GPL, but on a source-code level (that's how I understand MPL after all).

Obligatory: I am not a lawyer.

Either way, thanks for working on this!

**Comment by ysndr** [comment]
Hej Matthias

Glad you like the efforts of this project!
However, I'm sorry to disappoint

Currently the library is under LGPL because parts of it are implemented by statically linking to nix libraries, albeit through a separate binary that is currently not shipped with this library either https://github.com/flox/runix/issues/51.

Further there were plans to integrate closer with nix natively, through the C-API one day.
Unfortunately (for this library) our approach to using Nix changed, leading to efforts being diverted away from runix.
I'm hoping to bring this back to at least a state where use of and addition to this by the community is possible, but at the moment we are pursuing other priorities.

**Comment by matthiasbeyer** [comment]
Okay, thanks for responding anyways!
